### ISSUE TITLE
Focus Browser Window when opening something in Browser

### ISSUE THREAD

**Issue by juliansko** [pop-os/cosmic-epoch#1380] opened 2024-12-18 19:32 UTC
Hi, I would like to make one suggestion, it's to open (or give the option to do so) the window or switch to the workspace when opening something in the browser (clicking on a link in another application for example). Right now the links are opening correctly in Firefox but it stays in the wrong workspace so there is no indicator of whether it actually opened.

**Comment by leviport** [comment] 2024-12-18 19:47
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/637

**Closed by leviport** 2024-12-18 19:47 UTC
