### ISSUE TITLE
Clicking a link in Slack does not bring Brave to the front

### ISSUE THREAD

**Issue by bartv42** [pop-os/cosmic-epoch#440] opened 2024-07-18 07:00 UTC
Opening links from other apps does not seem to raise the browser to the front, which makes it seem nothing happens. I ended up with 10 new tabs the first time ;-)

**Comment by Drakulix** [comment] 2024-07-18 12:08
Duplicate of https://github.com/pop-os/cosmic-comp/issues/192

**Closed by Drakulix** 2024-07-18 12:08 UTC
