### ISSUE TITLE
Launching a zoom meeting from an invite link results in black screen

### ISSUE THREAD

**Issue by mkellyxp** [pop-os/cosmic-epoch#739] opened 2024-08-16 21:05 UTC
Clicking a zoom link invite link launches zoom but then freezes on a black window. 

Pop_OS alpha is fully up to date an rebooted as of this post, and zoom was installed via flatpak and was also up to date before launching.

The same zoom flatpak and link launch fine in both NixOS and Linux Mint

![screenshot-2024-08-16-21-01-07](https://github.com/user-attachments/assets/1fb3e73d-112a-4f61-88dd-19aa5d041fad)

**Comment by Zie0** [comment] 2024-08-17 14:14
This is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/736

**Closed** 2024-08-19 12:49 UTC
