### ISSUE TITLE
Pop!_OS / Wayland window placement (windows remember where they were)

### ISSUE THREAD

**Issue by robertstrom** [pop-os/cosmic-epoch#1262] opened 2024-11-20 02:45 UTC
I am sorry if this has been addressed before but I have got to ask / got to know.

From what I can tell a "feature" of Wayland is that it does not allow application windows to remember where they were and reopen in the same position they were in when closed.

Is that correct?

Will Pop!_OS have this same limitation when Cosmic is fully baked?

I don't know about others but the more I use Wayland, the more infuriated I get. This Wayland thing seems like a step back into the dark ages when it comes to certain functions and capabilities that we have all come to expect.

I don't want a window manager telling me that I am not allowed to have my windows open where I want them to be.

And, as I have mentioned before, other core programs (at least to me and I'm sure many others) either don't work, or work like crap. Examples:

- Flameshot / pretty much any decent screenshot program. Anything except the most basic of screenshot programs.
- CopyQ - clipboard managers same thing. Anything but the most basic just do not work well, or not at all.

And ... and ... NO ONE DOES Wayland the same. You never know what is going to work on what platform. Definition of INSANITY!

So ... cannot open windows in the position where you want them to open and other core programs don't work ...

Wayland ... three strikes ... ?

Someone please tell me that this is not the accepted future of Linux.

I personally see, and see many, many posts about the Wayland abomination (IMHO).

Why is this better ... convince me .. doubtful, but you can try

**Comment by leviport** [comment] 2024-11-20 14:52
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/325

Also, relax a bit. COSMIC DE is still in alpha, and this is just one of the many things that simply still needs work. We aren't trying to infuriate you.

**Closed by leviport** 2024-11-20 14:52 UTC

**Comment by robertstrom** [comment] 2024-11-21 01:17
I know that it is still in Alpha. I'm trying to get an understanding of what the future of Pop!_OS will look like and how much the fact that it is using Wayland will influence how it behaves and what limitations there might be. Because ... there is not much, maybe not anything, that I can see that I like about Wayland at this time. I will look at 325.

Thanks!

**Comment by robertstrom** [comment] 2024-11-21 01:22
'Doh .... needs upstream support from Wayland ... sigh ... I'm going to have nightmares now.

I will still keep using Pop!_OS ... for now. This has been my favorite Linux distro for several years now. Pop and Kali.

If these Wayland issues cannot get resolved then I think that I will have to move to something with an i3wm. Wayland is, even after I think 15 years ish now, way, way to immature for my taste. To be frank it seems like a huge cluster to me.

Looking forward to see how you deal with these issues ... if you can.

Thanks!
