### ISSUE TITLE
Feature request: Blue light filter

### ISSUE THREAD

**Issue by nvkomata** [pop-os/cosmic-epoch#514] opened 2024-08-08 21:01 UTC
a simple blue light filter (configurable temperature of your screens' colors?)

optionally should be able to disable/enable based on the time of day

**Comment by git-f0x** [comment] 2024-08-08 21:10
This is planned, but since it's part of a larger color management story (including HDR), Night Light will be added post-release.

**Comment by jokeyrhyme** [comment] 2024-08-09 11:53
Possibly a duplicate of https://github.com/pop-os/cosmic-epoch/issues/476

**Comment by leviport** [comment] 2024-08-12 10:17
Closing as a duplicate of https://github.com/pop-os/cosmic-epoch/issues/476

**Closed by leviport** 2024-08-12 10:17 UTC
