### ISSUE TITLE
About touchscreen support

### ISSUE THREAD

**Issue by Elecleus** [pop-os/cosmic-epoch#1419] opened 2024-12-30 15:52 UTC
Most of cosmic app do not support touchscreen now.

When will touchscreen support be added to these apps?

Will touchscreen functionality be a significant part of future development?

**Comment by leviport** [comment] 2024-12-30 16:28
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/241

**Closed by leviport** 2024-12-30 16:28 UTC
