### ISSUE TITLE
Poor performance copying large amounts of files (photos) and generating thumbnails.

### ISSUE THREAD

**Issue by glep-gif** [pop-os/cosmic-epoch#1015] opened 2024-09-26 19:22 UTC
Copying a few hundred photos (jpg and raw) from an SD card seems very CPU/ram intensive in cosmic. It can cause the file browser to crash, halting the transfer. Similarly, scrolling through a directory with a large number of images causes large amounts of cpu usage, completely locking up the system while it generates thumbnails. On a cheap laptop with these specs: 

```
OS: Pop!_OS 22.04 LTS x86_64
Host: 82YU Lenovo V15 G4 AMN
Kernel: 6.9.3-76060903-generic
DE: COSMIC
CPU: AMD Ryzen 5 7520U with Radeon Graphics (8) @ 2.800GHz
GPU: AMD ATI 04:00.0 Device 1506
Memory: 3217MiB / 5745MiB
```

Performing the same operations under gnome does not hang/crash but I have not directly compared their cpu/ram usage.
Thanks. Apologies if I missed any basic steps/info.

**Comment by alphabitserial** [comment] 2024-09-27 19:13
Duplicate of https://github.com/pop-os/cosmic-files/issues/501

**Comment by leviport** [comment] 2024-10-13 16:06
Closing as a duplicate

**Closed by leviport** 2024-10-13 16:06 UTC
