### ISSUE TITLE
Feature: File Manager. Honor .hidden file

### ISSUE THREAD

**Issue by mcoyle1960** [pop-os/cosmic-epoch#579] opened 2024-08-10 17:39 UTC
Cosmic Alpha, clean install on metal.

Currently, the File Manage does not respest the ._hidden_ file.

Folder names entered into .hidden should not be visible in the file manager.

**Comment by leviport** [comment] 2024-08-12 11:59
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/446

**Closed by leviport** 2024-08-12 11:59 UTC
