### ISSUE TITLE
SystemD Extension not Working

### ISSUE THREAD

**Issue by J0shuaT** [pop-os/cosmic-epoch#41] opened 2022-08-02 01:04 UTC
@Drakulix Sorry to bother again, but my systemd extension isn't working. The build was completed successfully, and now I am trying to log into the COSMIC desktop. The documentation says there is an system-extension in the directory `~/cosmic-epoch/cosmic-sysext`. I believe the extension is in `~/cosmic-epoch/cosmic-sysext/usr/lib/systemd/user`, and it is named `cosmic-session.target`. Anyway I needed to put the file in `/var/lib/extensions/` a directory that didn't exist by default. I created the directory, put the file inside _without_ renaming it, and then restarted my laptop. However, there was no COSMIC option at the login screen. I also tried a couple other files in `~/cosmic-epoch/cosmic-sysext`, and then tried refreshing with `sudo systemd-sysext --refresh`. Refreshing didn't work with the dashes in front of the word `refresh`. When I removed the dashes and ran the command, it output: `No extensions found.`. Am I doing something wrong??

**Comment by J0shuaT** [comment] 2022-08-02 01:35
Update: I was able to log in to `COSMIC` after copying the entire `cosmic-sysext` folder to `/var/lib/extensions`. However the desktop looks nothing like what I expected. There is a huge top bar with big icons. Keyboard shortcuts don't do anything, and there isn't a wallpaper, just a plain grey background. All the UI elements have sharp corners. I saw a screenshot of the COSMIC desktop in another issue, and it looked nothing like what I just logged into. This is how I _thought_ it would look: https://user-images.githubusercontent.com/57502897/181655017-21d5af4f-0322-4cab-a133-21c985ecdf84.gif

**Comment by hojjatabdollahi** [comment] 2022-08-02 02:30
@J0shuaT Those screenshots are Figma prototypes: https://www.figma.com/proto/Vl3y5ug2i6IQYQFI1zxv6o/Cosmic-Tiling-Prototyping?node-id=216%3A10661&starting-point-node-id=216%3A13321

I don't think the current COSMIC desktop is anywhere near that level of polish. 
(I'm not associated with system76, so maybe they can clear it up for you).

**Comment by J0shuaT** [comment] 2022-08-02 02:45
@hojjatabdollahi Oh wow, thanks for telling me. I guess I should just wait to test the  COSMIC desktop since it isn't usable now. How were those prototypes created?

**Comment by hojjatabdollahi** [comment] 2022-08-02 04:04
You can use figma.com to prototype GUI interfaces. Even make it interactive. The System76 designers are using that to share their designs and visions and iterate. Check out that website. It's free for personal use.

**Comment by Drakulix** [comment] 2022-08-02 09:28
>  I saw a screenshot of the COSMIC desktop in another issue, and it looked nothing like what I just logged into.

> I don't think the current COSMIC desktop is anywhere near that level of polish. (I'm not associated with system76, so maybe they can clear it up for you).

Right, those are design prototypes (without any functionality). We are still deep into the progress of making COSMIC DE function as intended, what you are seeing as a desktop is a very very early prototype not representing the final product.

A lot of features you expect like wallpapers or rounded corners are of cosmetic nature and not our focus right now as core functionality is still missing. Shortcuts are currently used to facilitate testing and don't necessarily work the same way. The desktop you are looking for does not exist yet, but we are working hard to make it reality!

> I was able to log in to COSMIC after copying the entire cosmic-sysext folder to /var/lib/extensions. 

That is exactly the intended way to install the DE at the moment (again for testing). Systemd extensions are not necessarily files, but directory trees or images. The original issue seems to be resolved, I am closing this for now, but feel free to continue discussing or asking questions.

**Closed by Drakulix** 2022-08-02 09:28 UTC

**Comment by J0shuaT** [comment] 2022-08-02 11:37
> A lot of features you expect like wallpapers or rounded corners are of cosmetic nature and not our focus right now as core functionality is still missing. Shortcuts are currently used to facilitate testing and don't necessarily work the same way. The desktop you are looking for does not exist yet, but we are working hard to make it reality!

@Drakulix thanks for your help, I completely understand. I'll be waiting for the final product of COSMIC DE! :D
