### ISSUE TITLE
Shutdown pop up not rendered correctly

### ISSUE THREAD

**Issue by Eddi-S** [pop-os/cosmic-epoch#1236] opened 2024-11-10 11:27 UTC
When I click the shutdown button in the system tray and then chooses shutdown
![screenshot-2024-11-10-11-25-18](https://github.com/user-attachments/assets/cf8a154c-ffef-4ff8-89c0-6f815205ce9f)
Then the shutdown pop up is not rendered correctly
![screenshot-2024-11-10-11-21-37](https://github.com/user-attachments/assets/47655579-04bf-454e-b042-145b9202c6f2)

**Comment by leviport** [comment] 2024-11-11 15:52
I believe I've seen this as well, when I was using a 4k display at 200% scaling. What scaling factor is your display?

**Comment by Eddi-S** [comment] 2024-11-11 16:00
4k resolution with 200% scaling

![screenshot-2024-11-11-15-59-06](https://github.com/user-attachments/assets/85d34e54-eeb3-4155-93fe-2d333a0fe195)

**Comment by leviport** [comment] 2024-11-11 16:12
Thanks, that's what I figured. This is definitely related to scaling then.

**Comment by git-f0x** [comment] 2024-11-11 17:34
There's also this issue: pop-os/cosmic-applets#716, and I think I've seen a few others as well reporting this issue.

**Comment by leviport** [comment] 2024-11-11 17:37
Ah you're right, I think this is a duplicate of https://github.com/pop-os/cosmic-applets/issues/716. I'll close this one and we can track the bug there.

**Closed by leviport** 2024-11-11 17:37 UTC
Labels: bug
