### ISSUE TITLE
Can't click on a context menu that overlaps the dock.

### ISSUE THREAD

**Issue by vadimk1337** [pop-os/cosmic-epoch#860] opened 2024-08-30 23:11 UTC
Cannot click create qr code in chromium browser

![screenshot-2024-08-30-23-06-30](https://github.com/user-attachments/assets/fca7f924-a0f6-4507-9fa6-4971360421db)

**Comment by git-f0x** [comment] 2024-08-30 23:40
Duplicate of pop-os/cosmic-comp#418.

**Closed** 2024-08-30 23:42 UTC
