### ISSUE TITLE
Repoman doesn't work

### ISSUE THREAD

**Issue by farhatizakaria** [pop-os/cosmic-epoch#770] opened 2024-08-19 22:44 UTC
when I use repoman command I got (for the GUI it doesn't launch): 
```
Traceback (most recent call last):
  File "/usr/bin/repoman", line 57, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 31, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .dialog import ErrorDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 28, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

**Solution:**

1. Install the Required Library

Make sure you have the libnotify library and its Python bindings installed on your system.  You can install these with:

`sudo apt-get install libnotify-bin python3-gi`

You might also need the python3-gi package for Python 3 support.

2. Install gi.repository.Notify Module

You may also need to install the libnotify development package if it’s not already installed:

`sudo apt-get install libnotify-dev`

**Comment by leviport** [comment] 2024-08-19 22:47
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/692

It looks like https://github.com/pop-os/cosmic-epoch/issues/692 has a different solution, but it definitely sounds like this is a dependency issue.

**Closed by leviport** 2024-08-19 22:47 UTC
