### ISSUE TITLE
[FEATURE REQUEST] Window Buttons Option To Move To Left Of Window

### ISSUE THREAD

**Issue by dsreyes1014** [pop-os/cosmic-epoch#1286] opened 2024-11-26 13:46 UTC
Low priority but wanted to feature request window buttons to have an option to be moved to the left and any sort of workspace/window overview to follow that option with close button placement.  Great job on this so far guys!

**Comment by leviport** [comment] 2024-11-26 16:05
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/640

**Closed by leviport** 2024-11-26 16:05 UTC
