### ISSUE TITLE
[Bug]: Workspace blank after Suspend

### ISSUE THREAD

**Issue by locomot1f** [pop-os/cosmic-epoch#925] opened 2024-09-10 15:14 UTC
Greetings,

after coming out of 'Suspend' mode I've noticed that my Workspace on my second monitor is blank. Even though there are windows / applications on the screen:
![PXL_20240910_150646561 RAW-01 COVER](https://github.com/user-attachments/assets/ac4de930-89fa-4ef4-8727-8c2d130b5c38)

Let me know if you need any additional information.

**Comment by nevdelap** [comment] 2024-09-12 23:09
I get this after Cosmic has been open for some time, though I don't know how long - but I don't suspend my machine. I had thought it was happening after locking and unlocking, but it is not that either because since pop-os/cosmic-greeter#126 I've disabled my lock screen shortcut and haven't been locking my screen (home machine), so it is not that either.

![image](https://github.com/user-attachments/assets/058913c9-23d9-4f6a-bb95-5c982df05e0e)

**Comment by nevdelap** [comment] 2024-09-12 23:13
@locomot1f , you might want to close this off as a duplicate of pop-os/cosmic-workspaces-epoch#61.

**Comment by LeonDBL** [comment] 2024-09-13 09:53
I've had to double check, but leaving my machine running not logging out or suspending; after a while and if I come back to my machine, DE environment is gone and computer wakes to what looks like boot messages. When the desktop returns all my open programmes have been closed.

**Comment by nevdelap** [comment] 2024-09-13 12:45
@LeonDBL, this issue is specifically about the issue shown in the screenshot. The empty workspace switcher across the top of the screen.

**Comment by LeonDBL** [comment] 2024-09-13 14:05
> @LeonDBL, this issue is specifically about the issue shown in the screenshot. The empty workspace switcher across the top of the screen.

OK, my bad. I'll open a new issue.

**Closed** 2024-11-20 16:31 UTC
