### ISSUE TITLE
input sources disappear after update

### ISSUE THREAD

**Issue by qdab** [pop-os/cosmic-epoch#935] opened 2024-09-13 12:31 UTC
added Arabic & updated immediately, then only it defaulted to only English.

not a major issue to me just would like to document the issue.

happened every update since first alpha.

**Comment by leviport** [comment] 2024-09-13 14:30
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/614

**Closed by leviport** 2024-09-13 14:30 UTC
