### ISSUE TITLE
Icons missing on one machine but not on others

### ISSUE THREAD

**Issue by cfuehrmann** [pop-os/cosmic-epoch#459] opened 2024-07-28 09:53 UTC
I have three Arch machines running cosmic-session-git, one CachyOS and two EndeavourOS. On one of the EndeavourOS machines, the Cosmic dialogs have black boxes instead of icons, see this example this screenshot:

![Desktop - COSMIC Settings_2024-07-28_114541_7487](https://github.com/user-attachments/assets/c5cca68d-0e99-4916-81f7-d3f24b33aee5)

**Comment by mmstick** [comment] 2024-07-29 12:22
Duplicate of #451

**Closed by mmstick** 2024-07-29 12:22 UTC
