### ISSUE TITLE
Feature Request: Limit dock applications to screen/workspace

### ISSUE THREAD

**Issue by matdave** [pop-os/cosmic-epoch#1270] opened 2024-11-21 19:37 UTC
Currently, all open apps show on the dock. It would be ideal to have a way to toggle, limiting it to show only what is open on that screen or workspace.

**Comment by leviport** [comment] 2024-11-21 19:51
Duplicate of https://github.com/pop-os/cosmic-applets/issues/339

**Closed by leviport** 2024-11-21 19:51 UTC
