### ISSUE TITLE
Shift + Delete does not work on Cosmic Files

### ISSUE THREAD

**Issue by HPS88** [pop-os/cosmic-epoch#1013] opened 2024-09-26 19:01 UTC
I use this option a lot when working on project files, I wan to be able to permanently delete a file by doing Shift + Delete when the file or folder is selected. I prefer this to having to go clean the trash after deleting.

**Comment by leviport** [comment] 2024-10-13 15:55
Duplicate of https://github.com/pop-os/cosmic-files/issues/348

**Closed by leviport** 2024-10-13 15:55 UTC
