### ISSUE TITLE
Freeze when minimizing and maximizing windows

### ISSUE THREAD

**Issue by Ganipotes** [pop-os/cosmic-epoch#1197] opened 2024-10-30 23:25 UTC
When trying to resize windows with minimizing or maximizing, everything freeze.

On Fedora 41 with Secureblue version: 41.20241030.0 
Hdw: Framework amd

**Comment by pheki** [comment] 2024-12-02 15:32
Looks like a duplicate of https://github.com/pop-os/cosmic-comp/issues/887 and https://github.com/pop-os/cosmic-epoch/issues/1097

They're probably related to https://gitlab.freedesktop.org/drm/amd/-/issues/3693

**Closed** 2024-12-02 18:54 UTC
