### ISSUE TITLE
[Bug] Super + x + left click combination causes systematic crash of cosmic session

### ISSUE THREAD

**Issue by nevadeon** [pop-os/cosmic-epoch#1134] opened 2024-10-15 12:25 UTC
My work space behavior is set to tiled. When entering the swap windows mode with super + x shortcut if I left click anywayre in the grey area the entire cosmic session crashes and restarts.

Here is what I get from journalctl when this happens :

```cosmic-comp[18830]: thread 'surface-eDP-1' panicked at 'internal error: entered unreachable code': src/shell/layout/tiling/mod.rs:5163
cosmic-comp[18830]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NodeIdNoLongerValid': src/shell/layout/tiling/mod.rs:864
kernel: nouveau 0000:01:00.0: Enabling HDA controller
kernel: nouveau 0000:01:00.0: bus: MMIO read of 00000000 FAULT at 122124 [ PRIVRING ]
cosmic-panel[18885]: com.system76.CosmicAppletNotifications: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletNotifications: thread '<unnamed>' panicked at /build/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/7016380/src/applet/token/wayland_handler.rs:174:50:
cosmic-panel[18885]: com.system76.CosmicAppletNotifications: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletNotifications: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletTime: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletTime: thread '<unnamed>' panicked at /build/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/7016380/src/applet/token/wayland_handler.rs:174:50:
cosmic-panel[18885]: com.system76.CosmicAppletTime: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletTime: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: thread '<unnamed>' panicked at cosmic-applet-minimize/src/wayland_handler.rs:507:50:
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletNotifications: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletTime: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletTiling: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletTiling: thread '<unnamed>' panicked at cosmic-applet-tiling/src/wayland.rs:151:55:
cosmic-panel[18885]: com.system76.CosmicAppletTiling: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletTiling: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppList: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppList: thread '<unnamed>' panicked at cosmic-app-list/src/wayland_handler.rs:719:50:
cosmic-panel[18885]: com.system76.CosmicAppList: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppList: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletNetwork: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletNetwork: thread '<unnamed>' panicked at /build/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/7016380/src/applet/token/wayland_handler.rs:174:50:
cosmic-panel[18885]: com.system76.CosmicAppletNetwork: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletNetwork: stack backtrace:
cosmic-session[602]: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppList: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletNetwork: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletAudio: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletAudio: thread '<unnamed>' panicked at /build/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/7016380/src/applet/token/wayland_handler.rs:174:50:
cosmic-panel[18885]: com.system76.CosmicAppletAudio: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletAudio: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletAudio: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: thread 'main' panicked at cosmic-applet-minimize/src/lib.rs:125:21:
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: Wayland Subscription ended...
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletBattery: Io error: Broken pipe (os error 32)
cosmic-panel[18885]: com.system76.CosmicAppletBattery: thread '<unnamed>' panicked at /build/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/7016380/src/applet/token/wayland_handler.rs:174:50:
cosmic-panel[18885]: com.system76.CosmicAppletBattery: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
cosmic-panel[18885]: com.system76.CosmicAppletBattery: stack backtrace:
cosmic-panel[18885]: com.system76.CosmicAppletBattery: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: com.system76.CosmicAppletTiling: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cosmic-panel[18885]: process ' X_MINIMIZE_APPLET=true X_PRIVILEGED_WAYLAND_SOCKET=110 COSMIC_PANEL_NAME=Dock COSMIC_PANEL_SIZE=L COSMIC_PANEL_OUTPUT=eDP-1 COSMIC_PANEL_ANCHOR=Bottom COSMIC_PANEL_BACKGROUND=ThemeDefault RUST_BACKTRACE=1 WAYLAND_SOCKET=101 cosmic-applet-minimize ' failed with code 101
cosmic-panel[18885]: Exited with error code 101
pulseaudio[709]: X11 I/O error handler called
pulseaudio[709]: X11 I/O error exit handler called, preparing to tear down X11 modules
cosmic-session[602]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
cosmic-session[602]: cosmic-comp exited with error code 101
cosmic-session[602]: draining stdin receiver before restarting process
cosmic-session[602]: sleeping for 7ms before restarting process cosmic-comp (restart 0)
cosmic-session[602]: process 'ProcessKey(11v1)' cancelled
cosmic-session[602]: process 'ProcessKey(10v1)' cancelled
cosmic-session[602]: process 'ProcessKey(9v1)' cancelled
cosmic-session[602]: process 'ProcessKey(8v1)' cancelled
cosmic-session[602]: process 'ProcessKey(7v1)' cancelled
cosmic-session[602]: process 'ProcessKey(6v1)' cancelled
cosmic-session[602]: process 'ProcessKey(5v1)' cancelled
cosmic-session[602]: process 'ProcessKey(4v1)' cancelled
cosmic-session[602]: process 'ProcessKey(3v1)' cancelled
cosmic-session[602]: process 'ProcessKey(2v1)' cancelled
cosmic-session[602]: RESTARTING: session restarted by request
cosmic-session[602]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
cosmic-session[602]: process 'ProcessKey(1v1)' cancelled
systemd-coredump[19328]: Process 19019 (cosmic-panel-bu) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19329]: Process 18981 (cosmic-applet-t) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19330]: Process 19015 (cosmic-app-list) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19333]: Process 19013 (cosmic-panel-bu) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19331]: Process 19011 (cosmic-applet-s) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19335]: Process 18986 (cosmic-applet-i) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19332]: Process 19009 (cosmic-applet-a) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19337]: Process 18980 (cosmic-applet-n) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19334]: Process 18993 (cosmic-applet-n) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19336]: Process 18995 (cosmic-applet-p) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19341]: Process 18962 (cosmic-applet-t) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19338]: Process 19008 (cosmic-panel-bu) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19339]: Process 19301 (cosmic-applet-m) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd-coredump[19340]: Process 18967 (cosmic-applet-b) of user 1000 terminated abnormally with signal 6/ABRT, processing...
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: systemd-coredump.socket: Too many incoming connections (9) from source UID 0, dropping connection.
systemd[1]: Started Process Core Dump (PID 19328/UID 0).
systemd[1]: Started Process Core Dump (PID 19329/UID 0).
systemd[1]: Started Process Core Dump (PID 19330/UID 0).
systemd[1]: Started Process Core Dump (PID 19333/UID 0).
systemd[1]: Started Process Core Dump (PID 19331/UID 0).
systemd[1]: Started Process Core Dump (PID 19332/UID 0).
systemd[1]: Started Process Core Dump (PID 19335/UID 0).
systemd[1]: Started Process Core Dump (PID 19334/UID 0).
systemd-coredump[19349]: Process 18993 (cosmic-applet-n) of user 1000 dumped core.
systemd[1]: systemd-coredump@71-19334-0.service: Deactivated successfully.
systemd-coredump[19344]: Process 19015 (cosmic-app-list) of user 1000 dumped core.
systemd-coredump[19346]: Process 19011 (cosmic-applet-s) of user 1000 dumped core.
systemd[1]: systemd-coredump@66-19330-0.service: Deactivated successfully.
systemd[1]: systemd-coredump@68-19331-0.service: Deactivated successfully.
systemd-coredump[19343]: Process 18981 (cosmic-applet-t) of user 1000 dumped core.
systemd-coredump[19345]: Process 19013 (cosmic-panel-bu) of user 1000 dumped core.
systemd-coredump[19348]: Process 18986 (cosmic-applet-i) of user 1000 dumped core.
systemd[1]: systemd-coredump@65-19329-0.service: Deactivated successfully.
systemd-coredump[19342]: Process 19019 (cosmic-panel-bu) of user 1000 dumped core.
systemd[1]: systemd-coredump@67-19333-0.service: Deactivated successfully.
systemd[1]: systemd-coredump@64-19328-0.service: Deactivated successfully.
systemd[1]: systemd-coredump@70-19335-0.service: Deactivated successfully.
systemd-coredump[19347]: Process 19009 (cosmic-applet-a) of user 1000 dumped core.
systemd[1]: systemd-coredump@69-19332-0.service: Deactivated successfully.
systemd[1]: systemd-coredump@69-19332-0.service: Consumed 1.000s CPU time, 553.3M memory peak.
systemd[592]: Stopped target Cosmic Session Target.
systemd[592]: Stopped target Current graphical user session.
systemd[592]: Stopped target Session services which should run early before the graphical session is brought up.
systemd[592]: Stopped target Startup of XDG autostart applications.
cosmic-session[602]: Restarting```

**Comment by leviport** [comment] 2024-10-15 13:24
Duplicate of https://github.com/pop-os/cosmic-comp/issues/924

**Closed by leviport** 2024-10-15 13:24 UTC
