### ISSUE TITLE
[Feature request] key registration for shortucts

### ISSUE THREAD

**Issue by nevadeon** [pop-os/cosmic-epoch#1136] opened 2024-10-15 13:41 UTC
I don't know if it is a bug or a missing feature but it would be a nice thing to register a keyboard shortcut by actually doing the shortcut/pressing the keys instead of manually writing each key which I found to be quite error prone.

**Comment by leviport** [comment] 2024-10-15 14:09
Duplicate of https://github.com/pop-os/cosmic-settings/issues/499

**Closed by leviport** 2024-10-15 14:09 UTC
