### ISSUE TITLE
Input Source Configuration Issue: Second Input Source Disappears After Reboot

### ISSUE THREAD

**Issue by farhatizakaria** [pop-os/cosmic-epoch#842] opened 2024-08-27 17:37 UTC
**Description:** when adding a secondary input source, it does not persist after a system reboot. Only the primary input source remains available.

**Steps to Reproduce:**

1. Set a primary input source.
2. Add a secondary input source.
3. Reboot the system.
4. After rebooting, check the list of input sources.

**Expected Behavior:** Both primary and secondary input sources should be available after rebooting the system.

**Actual Behavior:** Only the primary input source is available after rebooting. The secondary input source is lost.

**Comment by leviport** [comment] 2024-08-27 17:42
I believe this is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/614

**Comment by otaviobrum** [comment] 2024-09-06 16:52
You don't even need to reboot the machine to lose the configuration, every time you close the session you will notice that the bug will be there again.

**Comment by mmstick** [comment] 2024-09-26 11:08
Fixed by https://github.com/pop-os/cosmic-settings-daemon/commit/ae00cf5e1e0cd021089e40a8c655d30c3490a0be

**Closed by mmstick** 2024-09-26 11:08 UTC
