### ISSUE TITLE
Cosmic DE on Arch icons are just black square.

### ISSUE THREAD

**Issue by NguyenHoangHieu22GIT2** [pop-os/cosmic-epoch#741] opened 2024-08-17 11:21 UTC
I just installed Cosmic DE on my arch today, and all of the icons are just black squares for no reason, please help? is this a bug from DE or it's my problem? either way support will be appreciated.
Specs:
Arch Linux - 16GB RAM - NVIDIA 3050 ( NVIDIA 555 ) - Intel I5 11400H
![image](https://github.com/user-attachments/assets/3e0bd50b-4343-4479-8526-7af29fe485ba)

**Comment by mmstick** [comment] 2024-08-17 11:26
Duplicate of #451 
You could ask the Arch maintainer to make Mesa's Vulkan driver a dependency of the packaging

**Closed by mmstick** 2024-08-17 11:26 UTC
