### ISSUE TITLE
[FEATURE REQUEST] Fullscreen toggle

### ISSUE THREAD

**Issue by bluescorpion35** [pop-os/cosmic-epoch#521] opened 2024-08-08 22:46 UTC
Add a toggle and a shortcut for fullscreen for all apps like sway does (Not just maximize).

**Comment by Drakulix** [comment] 2024-08-09 10:31
Duplicate of https://github.com/pop-os/cosmic-comp/issues/646

**Closed by Drakulix** 2024-08-09 10:31 UTC
