### ISSUE TITLE
Screen locker only works after re-login

### ISSUE THREAD

**Issue by cfuehrmann** [pop-os/cosmic-epoch#457] opened 2024-07-28 09:21 UTC
I have three Arch machines, two EndavourOS and on CachyOS. On each, I use cosmic-session-git. If have this problem on all machines:

When, after a reboot, I log into Cosmic via SDDM, then the lock screen won't trigger when I press Super+Esc or use "Lock Screen" via the power menu in the panel. But when I then log out of Cosmic and log in again via SDDM, the lock screen works!

**Comment by leviport** [comment] 2024-07-29 13:35
I believe this is a duplicate of https://github.com/pop-os/cosmic-greeter/issues/72

**Closed by leviport** 2024-07-29 13:35 UTC
