### ISSUE TITLE
PyCharm

### ISSUE THREAD

**Issue by pierre-sigwalt** [pop-os/cosmic-epoch#1057] opened 2024-10-02 00:30 UTC
Hello,

Dunno if other people have the issue but using PyCharm trying to add a new folder or new file we can't enter any names.

## Steps to reproduce

1. Open PyCharm Profesional (didn't try with community edition)
2. Create new Project
3. Project Tree -> Right Click -> New -> File or Folder
4. The window is well focused, entering any keyboard input nothing happen.

![screenshot-2024-10-02-00-28-36](https://github.com/user-attachments/assets/71324874-0b75-4cad-a87f-e58823d14dcd)
![screenshot-2024-10-02-00-28-49](https://github.com/user-attachments/assets/2adadf4d-b2f2-4d78-9a97-fa6ff5d9e0e1)

## Version
Nvidia / Cosmic alpha 2

``` text
$cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Pop!_OS 24.04 LTS"

```

**Comment by DenisV94** [comment] 2024-10-08 11:33
Same error in
IntelliJ IDEA 2024.2.3 (Community Edition)
I supposes is IDEA global problem in cosmic.

Version:
Nvidia / Cosmic alpha 2
denis@pop-os:~$ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Pop!_OS 24.04 LTS"

**Comment by DenisV94** [comment] 2024-10-11 10:51
The problem is solved enabling Wayland:
https://github.com/pop-os/cosmic-epoch/issues/966#issuecomment-2404433671
Read that post.

**Comment by leviport** [comment] 2024-10-14 20:16
Closing in favor of https://github.com/pop-os/cosmic-epoch/issues/966

**Closed by leviport** 2024-10-14 20:16 UTC
