### ISSUE TITLE
PopUp windows not receiving keyboard input

### ISSUE THREAD

**Issue by sasa-fajkovic** [pop-os/cosmic-epoch#1088] opened 2024-10-08 21:34 UTC
I just installed intelij idea community idea (from the PopOs store and using intelij toolbox) and the behaviour was completely the same in both scenarios.

When there is a new popup window which requires input from the keyboard (for example if you want to create a new file), no input from the keyboard is being sent to that window. Getting focus from a mouse works fine (window gets focus and cursor is blinking inside the text area), but the window can no longer be closed.

**Comment by muzzwood** [comment] 2024-10-11 04:34
I think this is the same issue: https://github.com/pop-os/cosmic-epoch/issues/966

**Comment by leviport** [comment] 2024-10-14 20:15
This does sound like a duplicate of https://github.com/pop-os/cosmic-epoch/issues/966. I can reopen it if I'm mistaken.

**Closed by leviport** 2024-10-14 20:15 UTC
