### ISSUE TITLE
Cosmic Store crashes on launch

### ISSUE THREAD

**Issue by Frosty1442** [pop-os/cosmic-epoch#1352] opened 2024-12-13 00:08 UTC
When I run cosmic store I get the following message:
```
$ RUST_BACKTRACE=full cosmic-store
[2024-12-13T00:04:11Z WARN  wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
[2024-12-13T00:04:11Z WARN  sctk_adwaita::buttons] Ignoring unknown button type:
thread 'main' panicked at /build/cosmic-store-w8z52E/cosmic-store-0.1.0~1733801879~22.04~bbcc650/vendor/iced_widget/src/scrollable.rs:1241:53:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x56ec2cef42b5 - <unknown>
   1:     0x56ec2cf22a8b - <unknown>
   2:     0x56ec2ceefd3f - <unknown>
   3:     0x56ec2cef408e - <unknown>
   4:     0x56ec2cef5779 - <unknown>
   5:     0x56ec2cef551a - <unknown>
   6:     0x56ec2cef5c13 - <unknown>
   7:     0x56ec2cef5abb - <unknown>
   8:     0x56ec2cef4779 - <unknown>
   9:     0x56ec2cef5827 - <unknown>
  10:     0x56ec2b66b073 - <unknown>
  11:     0x56ec2b66b11c - <unknown>
  12:     0x56ec2b66afd9 - <unknown>
  13:     0x56ec2ba71cc7 - <unknown>
  14:     0x56ec2b80aaa3 - <unknown>
  15:     0x56ec2b896ce2 - <unknown>
  16:     0x56ec2b897303 - <unknown>
  17:     0x56ec2ba21501 - <unknown>
  18:     0x56ec2ba22441 - <unknown>
  19:     0x56ec2b897303 - <unknown>
  20:     0x56ec2b9cd4fb - <unknown>
  21:     0x56ec2ba22441 - <unknown>
  22:     0x56ec2b897303 - <unknown>
  23:     0x56ec2b9cc7e1 - <unknown>
  24:     0x56ec2ba6357a - <unknown>
  25:     0x56ec2ba6af75 - <unknown>
  26:     0x56ec2ba9eef0 - <unknown>
  27:     0x56ec2ba6a222 - <unknown>
  28:     0x56ec2b70f807 - <unknown>
  29:     0x56ec2b90e1f5 - <unknown>
  30:     0x56ec2ba76873 - <unknown>
  31:     0x56ec2b885799 - <unknown>
  32:     0x56ec2cee764d - <unknown>
  33:     0x56ec2b90e445 - <unknown>
  34:     0x79bf25629d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  35:     0x79bf25629e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  36:     0x56ec2b66bb65 - <unknown>
  37:                0x0 - <unknown>
```

I am on Pop! OS 22.04 LTS kernel version 6.9.3-76060903-generic. I just ran apt update right now and I have no updates.

This happens both under GNOME and COSMIC

**Comment by leviport** [comment] 2024-12-13 00:16
Duplicate of https://github.com/pop-os/cosmic-store/issues/216

**Closed by leviport** 2024-12-13 00:16 UTC
