### ISSUE TITLE
No more  numlock on cosmic's app

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#1193] opened 2024-10-29 08:55 UTC
Numlock needs to be activated after every single reboot.
Except that, it used to work fine on all app.
However, for the last few days, numlock has stopped working on cosmic's app. It does work on other app such as Firefox but it doesn't work on cosmic terminal, cosmic files, cosmic text editor...

**Comment by Thatoo** [comment] 2024-10-29 11:57
it's weird because the key for the 5 in the numlock keyboard does work on cosmic's app also but only the 5...

**Comment by git-f0x** [comment] 2024-10-29 13:25
The 5 probably works because it doesn't have any associated action when NumLock is disabled. This is likely a regression with the Iced rebase of apps.

**Comment by WatchMkr** [comment] 2024-12-09 18:00
closing to track on https://github.com/pop-os/libcosmic/issues/702

**Closed by WatchMkr** 2024-12-09 18:00 UTC
