### ISSUE TITLE
[BUG] Blank window opens on startup

### ISSUE THREAD

**Issue by bluescorpion35** [pop-os/cosmic-epoch#827] opened 2024-08-25 21:41 UTC
When I load up the environment, a white window opens. It is titled `Wayland to X Recording Bridge`
![image](https://github.com/user-attachments/assets/819c545c-52f6-4562-81dc-64ee86b57660)
I assume this is xwayland, but it did not appear on sway or Pop_OS 24.04 alpha. I am on the latest arch version, although it was there as well when I tried a few months ago. It can be closed, but is still annoying

**Comment by Department-stack** [comment] 2024-08-26 00:25
also is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/706
I just close the window, nothing should be harmed in doing so

**Closed** 2024-08-26 12:04 UTC
