### ISSUE TITLE
Activating items in the system tray does not work for some apps

### ISSUE THREAD

**Issue by zoof** [pop-os/cosmic-epoch#789] opened 2024-08-22 01:15 UTC
For example, I can click on Bitwarden's tray icon and it displays three options: Show / Hide, Lock Vault and Exit.  Only exit works and clicking on either of the other options does nothing: 
![image](https://github.com/user-attachments/assets/32ebe6c1-9005-418a-9b3b-acedeec0fc00)

**Comment by Department-stack** [comment] 2024-08-22 01:23
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/705

**Closed** 2024-08-22 13:54 UTC
