### ISSUE TITLE
images dont render

### ISSUE THREAD

**Issue by refrogerator** [pop-os/cosmic-epoch#689] opened 2024-08-15 08:54 UTC
I'm using the cachyos/archlinux build of cosmic but I've also compiled cosmic-settings to confirm its not already fixed.

![image](https://github.com/user-attachments/assets/07cb5224-8617-43a6-a6da-6d52286051c1)

The panel and background work fine weirdly enough.
I've also been getting a few NoConfigDirectory errors.

**Comment by mmstick** [comment] 2024-08-15 08:58
Duplicate of #451 
Make sure you have installed the correct Mesa Vulkan drivers.

**Closed by mmstick** 2024-08-15 08:58 UTC
