### ISSUE TITLE
Applications Display White Screens During Startup

### ISSUE THREAD

**Issue by Justin-Bento** [pop-os/cosmic-epoch#1297] opened 2024-12-01 00:33 UTC
When starting a new session from boot on my device, an app automatically launches but initially renders as a white screen. While some apps eventually load into their full interface, I’ve encountered a few strange instances, such as:

- The Settings app displaying only a small square box in the middle of the screen, with no other content.
- Certain apps freezing mid-render, requiring a restart to function 
- Applications failing to scale correctly, leaving UI elements misaligned or partially off-screen.

These issues seem to occur inconsistently, making it challenging to pinpoint the root cause. If I can screen shot an example I'll share it in this thread.

- New update: If it's not rendering white for some reason the top bar and the bottom bar just randomly disappear for no reason. Whenever I use YouTube for extended videos.  

 It feels like there might be a rendering or initialization issue during startup. System Specs Below 

---

Operating System: Fedora Linux 40
Desktop Environment: COSMIC
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.11.10-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: Framework
Product Name: Laptop 16 (AMD Ryzen 7040 Series)
System Version: AG

**Comment by Justin-Bento** [comment] 2024-12-01 15:57
Here is an example of my issue where my computer didn't crash, it has something to do with: Wayland to X11 Video Bridge

![screenshot-2024-12-01-14-48-39](https://github.com/user-attachments/assets/ef943f25-bc29-4b42-9a8b-733baef11bb6)

**Comment by Department-stack** [comment] 2024-12-02 22:12
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/706

**Closed** 2024-12-02 22:40 UTC
