### ISSUE TITLE
Vs code settings getting reset 

### ISSUE THREAD

**Issue by Vedantpr0** [pop-os/cosmic-epoch#461] opened 2024-07-29 07:28 UTC
I am having this issue since last 2 days don't know what happened wrong works well with gnome setup but as soon as I login in cosmic it resets my settings.
To be clear there is no mess from my side i had a fresh reinstall.

The video attached shows exactly what happens 
Cc: @mmstick as have seen you lot active in solving issues on reddit,yt comments so tagging you.

**Comment by Vedantpr0** [comment] 2024-07-29 07:30
Uploading video_20240729_125031.mp4…

**Comment by mmstick** [comment] 2024-07-29 07:45
Duplicate of https://github.com/pop-os/libcosmic/issues/538

**Closed by mmstick** 2024-07-29 07:45 UTC
