### ISSUE TITLE
ALT + TAB behavior - not normal

### ISSUE THREAD

**Issue by robertstrom** [pop-os/cosmic-epoch#1120] opened 2024-10-13 16:00 UTC
For decades when using the ALT + TAB key combinations you would cycle from the current program to that last program used when you pressed ALT + TAB once.

The current behavior of ALT + TAB does not behave that way. I see a list of programs and have to cycle through the list to get to the last programs that I used.

Example:

- I am in Firefox. I have several Firefox windows open so there is a list of these FIrefox windows when I press ALT + TAB
- I have Obsidian open and it is at the bottom of the list
- The position of the programs in this "list" that you are presented when you ALT + TAB does not ever change
- So, when I want to move from Firefox to paste something into Obsidian I have to press ALT + TAB many times to get there even though it was the last program that I used. This is **not** normal ALT + TAB behavior

Also, if you happen to overshoot the program that you wanted to use when pressing ALT + TAB many times you cannot press the SHIFT + ALT + TAB combination to go backwards, you have to cycle through all the programs again. Again, **not** normal ALT + TAB behavior.

If I could take a screenshot of it I would but the Cosmic screenshot program provides no ability to delay before taking a screenshot and other screenshot programs like Flameshot do not work on Cosmic DE / Wayland.

**Comment by git-f0x** [comment] 2024-10-13 17:19
This is a known issue, and it's planned to be fixed.

**Comment by leviport** [comment] 2024-10-14 21:30
Duplicate of https://github.com/pop-os/cosmic-launcher/issues/173

**Closed by leviport** 2024-10-14 21:30 UTC

**Comment by scathaig** [comment] 2025-05-03 12:51
currently on cosmic-launcher 0.1.0~1744762023~24.04~77ca208 and alt-tab again will always select the next window in the list. using alt-tab twice should go back to the windows i came from. with the current behavior you cannot use alt-tab to switch between the same two windows instead each alt-tab will give you another window.

**Comment by danutsu** [comment] 2025-05-06 17:19
Hey all, I think this was incorrectly closed as duplicate of the alt+shift+tab issue. Alt+shift+tab doesn't solve this.

In pretty much all other desktop environments I've ever used, alt+tab goes to last application you've used right before this one. And that's re-evaluated every time you press it. So if you alternate between two applications, a single alt+tab will switch you back and forth every time.

Try it out! Have 5 applications started, work in one, then switch to another one (via alt+multiple tabs, or any other means). Now press alt+tab once (releasing both buttons), repeatedly. In any other desktop environment (Windows, Gnome, Plasma, Chrome OS, Mac, whatever) you will be alternating between those two applications, no matter how many times you do it. You don't even have to look at the list! It's as if the other 3 applications don't even exist. In Cosmic you'll be going to other applications. And alt+shift+tab doesn't help in any way (that only helps if I look at the list and need to navigate it up).

This really is incredibly important for productivity and there's a reason that every single desktop environment has implemented it this way! Please don't be different on this, this is basic desktop UX.

**Comment by git-f0x** [comment] 2025-05-06 17:22
This was correctly closed, but a recent change to the launcher caused the broken behavior. It's fixed with the latest commits.

**Comment by danutsu** [comment] 2025-05-06 17:31
Ah OK, thanks, I was fooled by the "duplicate" entry above. I'll try updating.

**Comment by gabrielbdornas** [comment] 2026-04-28 13:42
I've just updated my system to use the Pop!_OS 24.04 LTS, and it appears that I'm having a pretty similar problem with my Alt+Tab behavior.

Now, Alt+Tab shows a vertical list of apps rather than visual thumbnails, which can be difficult to navigate and sometimes sticks on the screen if triggered too quickly.

Is there any configuration to switch to the preview behavior?

**Comment by mmstick** [comment] 2026-04-28 14:23
@gabrielbdornas There is no other behavior. This is the first implementation of this feature in COSMIC.
