### ISSUE TITLE
Applets lose focus with window focus follow cursor 

### ISSUE THREAD

**Issue by prushton2** [pop-os/cosmic-epoch#1178] opened 2024-10-24 17:06 UTC
I am using arch and installed via `pacman -S cosmic`

**Issue:** Clicking on an applet and dragging the mouse down to interact with the applet sometimes makes the applet disappear. 

**Steps to reproduce:**
* Open cosmic settings
* Enable `Desktop -> Window management -> Focus follows cursor`
* Set `Desktop -> Window management -> Focus follows cursor delay in ms` to 0
* Place a window below an applet so the applet will overlay the window
* Click an applet
* Attempt to move the mouse over the applet
* Notice how the applet disappears because focus shifts to the window below the applet

**Expected Behavior:**
Applet is put in focus

**Comment by git-f0x** [comment] 2024-10-24 17:11
Duplicate of pop-os/cosmic-comp#922.

**Closed** 2024-10-24 17:30 UTC
