### ISSUE TITLE
[BUG] Bluetooth Toggle Setting Placement

### ISSUE THREAD

**Issue by zavastopher** [pop-os/cosmic-epoch#1211] opened 2024-11-02 20:03 UTC
# Description

The bluetooth toggle doesn't seem to scale properly when the cosmic settings window is scaled to half the screen size. The workspace is set to auto-tiling.

# System Details

**OS**: Fedora 41 (Workstation Edition)
**Operating System architecture**: x86_64
**Hardware Model**: Framework 13 FRANBMCP0B (AB)
**Memory**: 31.13 GiB
**Processor**: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
**Graphics**: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
**Display Dimensions**: 2256x1504
**Scale**: 150%

# Screen Shot of the Issue

![screenshot-2024-11-02-19-40-02](https://github.com/user-attachments/assets/5d095b2e-6617-41ea-a35c-a87eed03ed0f)

**Comment by l-const** [comment] 2024-11-02 23:41
Duplicate of: https://github.com/pop-os/cosmic-settings/issues/708

**Closed** 2024-11-03 00:29 UTC
