### ISSUE TITLE
[Feature Request] Disable Super Key Setting

### ISSUE THREAD

**Issue by refrogerator** [pop-os/cosmic-epoch#693] opened 2024-08-15 14:08 UTC
Currently there seems to be no way to disable the super key by itself triggering something.
![image](https://github.com/user-attachments/assets/0bf64bc9-2803-4467-9c31-f8c4832f7cbd)

**Comment by git-f0x** [comment] 2024-08-15 17:06
Duplicate of pop-os/cosmic-settings#472.

**Closed** 2024-08-15 17:09 UTC
