### ISSUE TITLE
Option to Disable Touchpad

### ISSUE THREAD

**Issue by Android789515** [pop-os/cosmic-epoch#938] opened 2024-09-13 23:57 UTC
Using a laptop with a dedicated mouse, I find that the touch pad gets in the way often.  There isn't yet an option in the settings to disable it.

**Comment by git-f0x** [comment] 2024-09-14 12:33
Duplicate of pop-os/cosmic-settings#183.

**Closed** 2024-09-14 15:10 UTC
