### ISSUE TITLE
Setting for automatic tiling doesn't seem to save between reboots

### ISSUE THREAD

**Issue by mkellyxp** [pop-os/cosmic-epoch#740] opened 2024-08-16 21:10 UTC
I've disabled automatic tiling via the applet.  And windows do not tile as expected.

But on reboot, it is re-enabled again.

![screenshot-2024-08-16-21-08-04](https://github.com/user-attachments/assets/adb203ad-4621-41df-a7c0-0e3ac02abb09)

And after reboot:
![screenshot-2024-08-16-21-11-53](https://github.com/user-attachments/assets/3f53bc0d-95c5-4ef6-b0d5-3c25718ead41)

**Comment by leviport** [comment] 2024-08-16 21:17
I believe this is a duplicate of https://github.com/pop-os/cosmic-comp/issues/740

It's a bit confusing that there are two toggles, but "New workspace behavior" is the initial state all workspaces will be in upon creation (including after boot). Then the "current workspace" switch is an override for the current state, for when a user wants a workspace to be different from that initial state.

Pinging @pop-os/ux, since this happened twice today. Maybe there's a clearer way to state what each toggle does?

**Comment by mkellyxp** [comment] 2024-08-18 00:47
Ahhh yes your right. I didn't even see this! Silly me

**Closed** 2024-08-22 17:21 UTC
