### ISSUE TITLE
[cosmic-session] Most recent build fails to start with SDDM or from the terminal

### ISSUE THREAD

**Issue by ywnkmn** [pop-os/cosmic-epoch#72] opened 2023-02-15 09:41 UTC
System config:

```
neofetch --stdout
ywnkmn@ROG 
---------- 
OS: Arch Linux x86_64 
Host: ROG Flow X16 GV601RW_GV601RW 1.0 
Kernel: 6.1.11-arch1-1 
Uptime: 10 mins 
Packages: 891 (pacman), 51 (flatpak) 
Shell: bash 5.1.16 
Resolution: 2560x1600 
DE: Plasma 5.26.5 
WM: kwin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 9 6900HS with Radeon Graphics (16) @ 3.300GHz 
GPU: AMD ATI Radeon 680M 
GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU 
Memory: 5416MiB / 31353MiB 
```

It simply restarts the SDDM when selecting the `COSMIC (Wayland)` option, only the cursor could be seen in the left-upper corner though

If run from the terminal it crashes with:

```
[ywnkmn@ROG bin]$ ./cosmic-session 
2023-02-15T09:39:07.777999Z  INFO cosmic_session: Starting cosmic-session
2023-02-15T09:39:09.782912Z  INFO cosmic_session: got environmental variables: [("WAYLAND_DISPLAY", "wayland-1"), ("DISPLAY", ":2")]
2023-02-15T09:39:09.797185Z ERROR panic: thread 'main' panicked at 'failed to start launcher: Process(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })': src/main.rs:124
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   8: cosmic_session::main::{{closure}}
   9: std::thread::local::LocalKey<T>::with
  10: tokio::runtime::scheduler::current_thread::Context::enter
  11: tokio::macros::scoped_tls::ScopedKey<T>::set
  12: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  13: tokio::runtime::Runtime::block_on
  14: cosmic_session::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
      std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
```

If run with `sudo`:

```[ywnkmn@ROG bin]$ sudo RUST_BACKTRACE=full ./cosmic-session 
2023-02-15T09:40:13.925330Z  INFO cosmic_session: Starting cosmic-session
Error: 
   0: failed to start systemd target
   1: I/O error: No such file or directory (os error 2)
   2: No such file or directory (os error 2)

Location:
   src/systemd.rs:7

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮                               
   4: cosmic_session::main::{{closure}}::h578b4fe52e2866a3
      at <unknown source file>:<unknown line>
   5: std::thread::local::LocalKey<T>::with::h018badde0147436f
      at <unknown source file>:<unknown line>
   6: tokio::runtime::scheduler::current_thread::Context::enter::h89b0bef8fec28665
      at <unknown source file>:<unknown line>
   7: tokio::macros::scoped_tls::ScopedKey<T>::set::h0f7cf84669072a1d
      at <unknown source file>:<unknown line>
   8: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h8984648bfb786199
      at <unknown source file>:<unknown line>
   9: tokio::runtime::Runtime::block_on::hcb3bbbda009dc8d1
      at <unknown source file>:<unknown line>
  10: cosmic_session::main::h32e7a387aa6e5453
      at <unknown source file>:<unknown line>
  11: std::sys_common::backtrace::__rust_begin_short_backtrace::h2d0c92d2a3c7d7db
      at <unknown source file>:<unknown line>
  12: std::rt::lang_start::{{closure}}::h966429a32d33c474
      at <unknown source file>:<unknown line>
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2e730c3fa855d1cd
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606
  14: std::panicking::try::do_call::h2452817705661d69
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483
  15: std::panicking::try::had9be61d7261a8f5
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447
  16: std::panic::catch_unwind::h0e0ee12d5e0e8c35
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137
  17: std::rt::lang_start_internal::{{closure}}::hdfa1f1493a65dae1
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148
  18: std::panicking::try::do_call::h5a2ac6628cbce239
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483
  19: std::panicking::try::h6b550c44d18ea4fc
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447
  20: std::panic::catch_unwind::hd574fc8a4fcd921a
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137
  21: std::rt::lang_start_internal::h4189ab0091a05404
      at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148
  22: main<unknown>
      at <unknown source file>:<unknown line>
  23: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  24: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

How i it related to the `tokio` lib? Or what am I doing incorrectly?

**Comment by Drakulix** [comment] 2023-02-15 12:07
This looks like a duplicate of https://github.com/pop-os/cosmic-epoch/issues/71

**Comment by Drakulix** [comment] 2023-02-15 20:15
Should be fixed by https://github.com/pop-os/cosmic-epoch/pull/73. If not please reopen.

**Closed by Drakulix** 2023-02-15 20:15 UTC
