### ISSUE TITLE
terminal does not add file path when directory is dropped within terminal  

### ISSUE THREAD

**Issue by dnodno** [pop-os/cosmic-epoch#837] opened 2024-08-27 14:06 UTC
as the title says, Cosmic does not add file path to terminal when dragging a directory from file browser into terminal. It's a useful feature of Plasma to save time when doing file operations within terminal

**Comment by leviport** [comment] 2024-08-27 14:08
Duplicate of https://github.com/pop-os/cosmic-term/issues/86 which was implemented. Make sure you're fully up-to-date.

**Closed by leviport** 2024-08-27 14:08 UTC
