### ISSUE TITLE
consider apps being used in locations with bad network and low speed

### ISSUE THREAD

**Issue by itskazemk** [pop-os/cosmic-epoch#1268] opened 2024-11-21 05:18 UTC
As a user in Iran, I'd be glad if you guys considered us with poor internet that it's low speed or even sometimes we are blocked and can't ping some IPs. for example, I mean using several servers for download or saving downloaded file that if something went wrong it could download rest of it next time.
Thanks you all for pushing Linux world forward

**Comment by git-f0x** [comment] 2024-11-21 10:55
This isn't really related to the desktop environment. That's all up to distros and their repos and package managers.

**Comment by leviport** [comment] 2024-11-21 14:36
Duplicate of https://github.com/pop-os/cosmic-store/issues/210 

Since cosmic-store is probably the main application we're making that uses the network much, I'm going to close this issue and leave that one open. The rest, as Fox said, has more to do with distros and individual applications.

**Closed by leviport** 2024-11-21 14:36 UTC

**Comment by itskazemk** [comment] 2024-11-23 05:16
I know, I just wanted you guys to consider us in Iran with bad internet. It's a huge problem for me when I'm using Linux because most apps rely heavily on the Internet nowadays.  Thanks
