### ISSUE TITLE
Keyboard layout not persistent after reboot

### ISSUE THREAD

**Issue by N0m4n904** [pop-os/cosmic-epoch#614] opened 2024-08-11 13:08 UTC
I am on Arch and installed COSMIC. I went to the COSMIC Settings and changed the keyboard layout to German. After a reboot it get's reverted back to Englisch (US)

Is there any fix for it?

**Comment by leviport** [comment] 2024-08-13 16:48
I believe this is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/610

**Comment by aacebedo** [comment] 2024-08-28 06:36
Same on my side with nixos.
this specific bug basically prevents me to use on a daily basis.

**Comment by lrosenfeldt** [comment] 2024-09-05 20:15
Same on my Pop OS machine. If anybody is looking for a workaround, you can edit the config file `/etc/default/keyboard` directly though you need sudo privileges. Available keyboard layouts, variants and information about them can be found in `/usr/share/X11/xkb/rules/base.lst`, but I would recommend to check out `man keyboard` to find the right paths for your system. The changes take effect after an reboot.

On my machine the cosmic keyboard applet correctly displays the manually configured layout.

**Comment by otaviobrum** [comment] 2024-09-06 16:41
Same on my side with Fedora 40. I noticed that you don't need to reboot the machine to lose the configuration, if you close the session when logging in the bug will be there. In my case it always goes back to br and I lose the br-thinkpad configuration. This happens even when I delete the entry and leave only the one I want.

**Comment by husseinraoouf** [comment] 2024-09-17 15:45
this should be a priority, it prevents day to day usage for any one writing in non English language

**Comment by mmstick** [comment] 2024-09-26 11:08
Fixed by https://github.com/pop-os/cosmic-settings-daemon/commit/ae00cf5e1e0cd021089e40a8c655d30c3490a0be

**Closed by mmstick** 2024-09-26 11:08 UTC
