### ISSUE TITLE
[BUG] COSMIC Terminal + btop = Graphical Glitch.

### ISSUE THREAD

**Issue by Querzion** [pop-os/cosmic-epoch#408] opened 2024-06-30 15:32 UTC
![screenshot-2024-06-30-15-15-34](https://github.com/pop-os/cosmic-epoch/assets/39269026/d8d58f90-d1ec-4b01-ba0a-4a0b51e9ed8a)

**Comment by leviport** [comment] 2024-07-01 13:22
Duplicate of https://github.com/pop-os/cosmic-text/issues/237

**Closed by leviport** 2024-07-01 13:22 UTC
