### ISSUE TITLE
[Bug?] 16:10 weird YouTube 16:9 Video fullscreen

### ISSUE THREAD

**Issue by CosmicFusion** [pop-os/cosmic-epoch#381] opened 2024-06-07 08:43 UTC
Expected behavior: the video play-back stuff goes to the bottom, and there is a black bar above it and above the video, to fill out the video space. (Like windows,like gnome)

Current Cosmic behavior: 2 **gray** bars at top and bottom, the video playback toolbar goes on top the video and autohides, as if the display 16:9.

Not that severe, but definitely weird

Make it like gnome, or make the gray bars black.

**Comment by leviport** [comment] 2024-06-07 12:37
Which browser? Can you share a screenshot?

**Comment by CosmicFusion** [comment] 2024-06-07 12:47
> Which browser?
Google Chrome

>Can you share a screenshot?

Gnome: 
![Screenshot from 2024-06-07 15-44-05](https://github.com/pop-os/cosmic-epoch/assets/83735213/55296c79-c42e-43a0-ad3d-9a3572c4ae3e)

Cosmic:
![screenshot-2024-06-07-12-42-53](https://github.com/pop-os/cosmic-epoch/assets/83735213/ec59025c-f152-479e-ba9c-82b73b1acd4b)

1920x1200 120hz Nvidia BTW

Also clicking on stuff in cosmic is annoying, the hitbox of stuff is a little off where it's icon is

**Comment by leviport** [comment] 2024-06-07 13:03
Thanks, I'll try recreating this once I have access to a different AR display

**Comment by git-f0x** [comment] 2024-06-10 14:36
Might be related to pop-os/cosmic-comp#487.

**Comment by leviport** [comment] 2024-06-11 14:51
Yeah I'm thinking this is probably a duplicate of https://github.com/pop-os/cosmic-comp/issues/487. I'll close for now, but we can reopen later if needed.

**Closed by leviport** 2024-06-11 14:51 UTC
