### ISSUE TITLE
[Feature Request] Blur for Blurred elements in the UI

### ISSUE THREAD

**Issue by Milli189** [pop-os/cosmic-epoch#1300] opened 2024-12-02 18:25 UTC
I saw another similar feature request #604 and in the comments they've talked about a "frosted effect", but I don't precisely know what that means, if it is a cooler word to say "blur" or it's an entire different effect.

What I'm asking for is to have blurred transparent elements in the ui that are actively being blurred, so that when you move something under it, it blurs that element too, I think MacOS does it the best.

I would love to see the dock blurred, the top panel and maybe the left menu or sidebar (or how it's called I'm not too technical) in the files app

**Comment by git-f0x** [comment] 2024-12-02 19:02
Frosted glass effect is blur. It will apply to the panels, applets, menus, and possibly parts of apps (though the toolkit itself doesn't yet support blur, so some more fancy blur effects aren't possible, but a transparent blurred sidebar/window background is possible).

**Comment by leviport** [comment] 2024-12-02 19:30
This is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/604

**Closed by leviport** 2024-12-02 19:30 UTC

**Comment by Milli189** [comment] 2024-12-02 19:33
> Frosted glass effect is blur. It will apply to the panels, applets, menus, and possibly parts of apps (though the toolkit itself doesn't yet support blur, so some more fancy blur effects aren't possible, but a transparent blurred sidebar/window background is possible).

Thank you for the fast and extensive reply, I really appreciate it
