### ISSUE TITLE
[Bug] Monitor Power off closes all windows

### ISSUE THREAD

**Issue by mathsDOTearth** [pop-os/cosmic-epoch#1067] opened 2024-10-03 15:27 UTC
I am running Pop_OS! 24.04 and Cosmic desktop with latest updates
Computer: 
Dell Precision T7910
32GB RAM
Radeon Pro WX 5100

Issue:
If I power off my monitor, all of the windows (including running applications) close (closed not minimized). on powering the monitor on again I am still logged in but see a blank desk top and my applications/windows can not be re-opened.

Here is my system log covering the monitor power off and on time period:
024-10-03T15:17:01.582669+00:00 jam CRON[19121]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
2024-10-03T15:17:27.420336+00:00 jam kernel: workqueue: dm_irq_work_func [amdgpu] hogged CPU for >10000us 4 times, consider switching to WQ_UNBOUND
2024-10-03T15:17:27.586364+00:00 jam cosmic-comp[17977]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:973#012   0: <unknown>#012   1: <unknown>#012   2: <unknown>#012   3: <unknown>#012   4: <unknown>#012   5: <unknown>#012   6: <unknown>#012   7: <unknown>#012   8: <unknown>#012   9: <unknown>#012  10: <unknown>#012  11: <unknown>#012  12: <unknown>#012  13: <unknown>#012  14: <unknown>#012  15: <unknown>#012  16: __libc_start_call_main#012             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16#012  17: __libc_start_main_impl#012             at ./csu/../csu/libc-start.c:360:3#012  18: <unknown>
2024-10-03T15:17:27.586699+00:00 jam cosmic-comp[17977]: thread 'surface-DP-4' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': src/backend/kms/surface/mod.rs:1076#012   0: <unknown>#012   1: <unknown>#012   2: <unknown>#012   3: <unknown>#012   4: <unknown>#012   5: <unknown>#012   6: <unknown>#012   7: <unknown>#012   8: <unknown>#012   9: <unknown>#012  10: <unknown>#012  11: <unknown>#012  12: <unknown>#012  13: <unknown>#012  14: start_thread#012             at ./nptl/pthread_create.c:447:8#012  15: __GI___clone3#012             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
2024-10-03T15:17:27.601463+00:00 jam xdg-desktop-por[18312]: Error reading events from display: Broken pipe
2024-10-03T15:17:27.601840+00:00 jam cosmic-session[4951]: Io error: Broken pipe (os error 32)
2024-10-03T15:17:27.601940+00:00 jam cosmic-session[4951]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
2024-10-03T15:17:27.608324+00:00 jam systemd[4915]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
2024-10-03T15:17:27.608452+00:00 jam systemd[4915]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
2024-10-03T15:17:27.695560+00:00 jam cosmic-session[4951]: cosmic-comp exited with error code 101
2024-10-03T15:17:27.697006+00:00 jam cosmic-session[4951]: draining stdin receiver before restarting process
2024-10-03T15:17:27.698534+00:00 jam cosmic-session[4951]: sleeping for 5ms before restarting process cosmic-comp (restart 0)
2024-10-03T15:17:27.700132+00:00 jam cosmic-session[4951]: process 'ProcessKey(11v1)' cancelled
2024-10-03T15:17:27.701674+00:00 jam cosmic-session[4951]: process 'ProcessKey(10v1)' cancelled
2024-10-03T15:17:27.703197+00:00 jam cosmic-session[4951]: process 'ProcessKey(9v1)' cancelled
2024-10-03T15:17:27.704238+00:00 jam cosmic-session[4951]: process 'ProcessKey(8v1)' cancelled
2024-10-03T15:17:27.705223+00:00 jam cosmic-session[4951]: process 'ProcessKey(7v1)' cancelled
2024-10-03T15:17:27.706253+00:00 jam cosmic-session[4951]: process 'ProcessKey(6v1)' cancelled
2024-10-03T15:17:27.706878+00:00 jam cosmic-session[4951]: process 'ProcessKey(5v1)' cancelled
2024-10-03T15:17:27.707785+00:00 jam cosmic-session[4951]: process 'ProcessKey(4v1)' cancelled
2024-10-03T15:17:27.709226+00:00 jam cosmic-session[4951]: process 'ProcessKey(3v1)' cancelled
2024-10-03T15:17:27.709817+00:00 jam cosmic-session[4951]: process 'ProcessKey(2v1)' cancelled
2024-10-03T15:17:27.710793+00:00 jam cosmic-session[4951]: RESTARTING: session restarted by request
2024-10-03T15:17:27.713095+00:00 jam agent[18274]: Geolocation service not in use
2024-10-03T15:17:27.713200+00:00 jam cosmic-session[4951]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
2024-10-03T15:17:27.714261+00:00 jam cosmic-session[4951]: process 'ProcessKey(1v1)' cancelled
2024-10-03T15:17:28.541604+00:00 jam systemd[4915]: app-cosmic-com.system76.CosmicAppList-18495.scope: Consumed 1min 21.100s CPU time.
2024-10-03T15:17:29.722072+00:00 jam systemd[4915]: Stopped target cosmic-session.target - Cosmic Session Target.
2024-10-03T15:17:29.725381+00:00 jam systemd[4915]: Stopped target xdg-desktop-autostart.target - Startup of XDG autostart applications.
2024-10-03T15:17:29.726072+00:00 jam cosmic-session[4951]: Restarting
2024-10-03T15:17:29.726491+00:00 jam dbus-broker[18296]: Dispatched 26 messages @ 10(±11)μs / message.
2024-10-03T15:17:29.726633+00:00 jam systemd[4915]: Stopping app-at\x2dspi\x2ddbus\x2dbus@autostart.service - AT-SPI D-Bus Bus...
2024-10-03T15:17:29.726733+00:00 jam systemd[4915]: Stopping app-geoclue\x2ddemo\x2dagent@autostart.service - Geoclue Demo agent...
2024-10-03T15:17:29.726884+00:00 jam systemd[4915]: Stopping app-print\x2dapplet@autostart.service - Print Queue Applet...
2024-10-03T15:17:29.727313+00:00 jam systemd[4915]: Stopping gvfs-daemon.service - Virtual filesystem service...
2024-10-03T15:17:29.727444+00:00 jam cosmic-session[4951]: Starting cosmic-session
2024-10-03T15:17:29.727997+00:00 jam systemd[4915]: Stopping xdg-desktop-portal.service - Portal service...
2024-10-03T15:17:29.728558+00:00 jam cosmic-session[4951]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
2024-10-03T15:17:29.728766+00:00 jam systemd[4915]: Stopping xdg-document-portal.service - flatpak document portal service...
2024-10-03T15:17:29.729262+00:00 jam systemd[4915]: Stopping xdg-permission-store.service - sandboxed app permission store...
2024-10-03T15:17:29.732278+00:00 jam systemd[1]: run-user-1000-gvfs.mount: Deactivated successfully.
2024-10-03T15:17:29.734322+00:00 jam systemd[1]: run-user-1000-doc.mount: Deactivated successfully.
2024-10-03T15:17:29.734622+00:00 jam systemd[4915]: Stopped gvfs-daemon.service - Virtual filesystem service.
2024-10-03T15:17:29.735512+00:00 jam systemd[4915]: Stopped xdg-desktop-portal.service - Portal service.
2024-10-03T15:17:29.736488+00:00 jam systemd[4915]: Stopped xdg-document-portal.service - flatpak document portal service.
2024-10-03T15:17:29.737395+00:00 jam systemd[4915]: Stopped app-at\x2dspi\x2ddbus\x2dbus@autostart.service - AT-SPI D-Bus Bus.
2024-10-03T15:17:29.738225+00:00 jam systemd[4915]: Stopped app-geoclue\x2ddemo\x2dagent@autostart.service - Geoclue Demo agent.
2024-10-03T15:17:29.739086+00:00 jam systemd[4915]: Stopped app-print\x2dapplet@autostart.service - Print Queue Applet.
2024-10-03T15:17:29.739858+00:00 jam systemd[4915]: Stopped xdg-permission-store.service - sandboxed app permission store.
2024-10-03T15:17:29.741733+00:00 jam cosmic-comp[19221]: Failed to read config 'workspaces'
2024-10-03T15:17:29.741901+00:00 jam cosmic-comp[19221]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
2024-10-03T15:17:29.742017+00:00 jam cosmic-comp[19221]: Key-Binding 'Period' only matched case insensitive for "period"
2024-10-03T15:17:29.742098+00:00 jam cosmic-comp[19221]: Key-Binding 'Comma' only matched case insensitive for "comma"
2024-10-03T15:17:29.742159+00:00 jam cosmic-comp[19221]: Key-Binding 'Period' only matched case insensitive for "period"
2024-10-03T15:17:29.742213+00:00 jam cosmic-comp[19221]: Key-Binding 'Comma' only matched case insensitive for "comma"
2024-10-03T15:17:29.742274+00:00 jam cosmic-comp[19221]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2024-10-03T15:17:29.742498+00:00 jam cosmic-comp[19221]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2024-10-03T15:17:29.743311+00:00 jam systemd[4915]: Stopped target graphical-session.target - Current graphical user session.
2024-10-03T15:17:29.743608+00:00 jam systemd[4915]: Stopped target graphical-session-pre.target - Session services which should run early before the graphical session is brought up.
2024-10-03T15:17:29.806684+00:00 jam cosmic-comp[19221]: Unable to become drm master, assuming unprivileged mode
2024-10-03T15:17:29.898861+00:00 jam cosmic-comp[19221]: using legacy fbadd
2024-10-03T15:17:30.003532+00:00 jam cosmic-session[4951]: got environmental variables from cosmic-comp: [("DISPLAY", ":1"), ("WAYLAND_DISPLAY", "wayland-1")]
2024-10-03T15:17:30.009423+00:00 jam cosmic-session[4951]: starting process ' cosmic-settings-daemon '
2024-10-03T15:17:30.015081+00:00 jam acpid: client connected from 19289[1000:1000]
2024-10-03T15:17:30.015165+00:00 jam acpid: 1 client rule loaded
2024-10-03T15:17:30.037438+00:00 jam systemd[1]: Starting systemd-localed.service - Locale Service...
2024-10-03T15:17:30.038460+00:00 jam systemd[4915]: Starting session-migration.service - Session Migration...
2024-10-03T15:17:30.039521+00:00 jam systemd[4915]: Started ssh-agent.service - OpenSSH Agent.
2024-10-03T15:17:30.040609+00:00 jam systemd[4915]: Starting xdg-desktop-portal-rewrite-launchers.service - Rewrite dynamic launcher portal entries...
2024-10-03T15:17:30.041772+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland DAEMON_NOTIFICATIONS_FD=34 WAYLAND_SOCKET=37 cosmic-notifications '
2024-10-03T15:17:30.042805+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.042909+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland PANEL_NOTIFICATIONS_FD=29 WAYLAND_SOCKET=37 cosmic-panel '
2024-10-03T15:17:30.043952+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=37 cosmic-app-library '
2024-10-03T15:17:30.045196+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.045286+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=53 cosmic-launcher '
2024-10-03T15:17:30.046472+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.046567+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=67 cosmic-workspaces '
2024-10-03T15:17:30.047774+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.047874+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=76 cosmic-osd '
2024-10-03T15:17:30.048058+00:00 jam systemd[4915]: Finished session-migration.service - Session Migration.
2024-10-03T15:17:30.049258+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.049359+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=84 cosmic-bg '
2024-10-03T15:17:30.051310+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.051420+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=90 cosmic-greeter '
2024-10-03T15:17:30.052976+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.053084+00:00 jam cosmic-session[4951]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=99 PORTAL_WAYLAND_SOCKET=97 /usr/libexec/xdg-desktop-portal-cosmic '
2024-10-03T15:17:30.054679+00:00 jam cosmic-session[4951]: sending 1 fds
2024-10-03T15:17:30.055363+00:00 jam cosmic-session[4951]: sending 2 fds
2024-10-03T15:17:30.064806+00:00 jam cosmic-session[4951]: [2024-10-03T15:17:30Z ERROR cosmic_settings_subscriptions::upower::kbdbacklight] Error listening to KbdBacklight: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/UPower/KbdBacklight”
2024-10-03T15:17:30.067257+00:00 jam systemd[4915]: Started cosmic-app-library.scope.
2024-10-03T15:17:30.069052+00:00 jam systemd[4915]: Started cosmic-bg.scope.
2024-10-03T15:17:30.071456+00:00 jam systemd[4915]: Started cosmic-greeter.scope.
2024-10-03T15:17:30.073508+00:00 jam systemd[4915]: Started cosmic-launcher.scope.
2024-10-03T15:17:30.074147+00:00 jam cosmic-session[4951]: could not read cache file
2024-10-03T15:17:30.074267+00:00 jam cosmic-session[4951]: No such file or directory (os error 2)
2024-10-03T15:17:30.075723+00:00 jam systemd[4915]: Started cosmic-osd.scope.
2024-10-03T15:17:30.077978+00:00 jam systemd[4915]: Started cosmic-workspaces.scope.
2024-10-03T15:17:30.080526+00:00 jam systemd[4915]: Started xdg-desktop-portal-cosmic.scope.
2024-10-03T15:17:30.082764+00:00 jam systemd[4915]: Starting gvfs-daemon.service - Virtual filesystem service...
2024-10-03T15:17:30.085163+00:00 jam systemd[4915]: Starting xdg-desktop-portal.service - Portal service...
2024-10-03T15:17:30.100227+00:00 jam systemd[4915]: Started gvfs-daemon.service - Virtual filesystem service.
2024-10-03T15:17:30.105092+00:00 jam systemd[4915]: Finished xdg-desktop-portal-rewrite-launchers.service - Rewrite dynamic launcher portal entries.
2024-10-03T15:17:30.105223+00:00 jam systemd[1]: Started systemd-localed.service - Locale Service.
2024-10-03T15:17:30.107279+00:00 jam systemd[4915]: Reached target graphical-session-pre.target - Session services which should run early before the graphical session is brought up.
2024-10-03T15:17:30.108154+00:00 jam systemd[4915]: Reached target cosmic-session.target - Cosmic Session Target.
2024-10-03T15:17:30.108239+00:00 jam systemd[4915]: Reached target graphical-session.target - Current graphical user session.
2024-10-03T15:17:30.109511+00:00 jam systemd[4915]: Starting app-at\x2dspi\x2ddbus\x2dbus@autostart.service - AT-SPI D-Bus Bus...
2024-10-03T15:17:30.111711+00:00 jam systemd[4915]: Starting app-geoclue\x2ddemo\x2dagent@autostart.service - Geoclue Demo agent...
2024-10-03T15:17:30.114354+00:00 jam systemd[4915]: Starting app-gnome\x2dkeyring\x2dpkcs11@autostart.service - Certificate and Key Storage...
2024-10-03T15:17:30.121186+00:00 jam systemd[4915]: Starting app-gnome\x2dkeyring\x2dsecrets@autostart.service - Secret Storage Service...
2024-10-03T15:17:30.126873+00:00 jam systemd[4915]: Starting app-gnome\x2dkeyring\x2dssh@autostart.service - SSH Key Agent...
2024-10-03T15:17:30.127154+00:00 jam systemd[4915]: Starting app-im\x2dlaunch@autostart.service - im-launch...
2024-10-03T15:17:30.133315+00:00 jam systemd[4915]: Starting app-nm\x2dapplet@autostart.service - NetworkManager Applet...
2024-10-03T15:17:30.135834+00:00 jam systemd[4915]: Starting app-orca\x2dautostart@autostart.service - Orca Screen Reader...
2024-10-03T15:17:30.137483+00:00 jam systemd[4915]: Starting app-org.gnome.SettingsDaemon.DiskUtilityNotify@autostart.service - gnome-disk-utility notification plugin for GNOME Settings Daemon...
2024-10-03T15:17:30.139337+00:00 jam systemd[4915]: Starting app-org.pop_os.transition.Notify@autostart.service - Flatpak Transition...
2024-10-03T15:17:30.140879+00:00 jam systemd[4915]: Starting app-polkit\x2dgnome\x2dauthentication\x2dagent\x2d1@autostart.service - PolicyKit Authentication Agent...
2024-10-03T15:17:30.142883+00:00 jam systemd[4915]: Starting app-pop\x2dapp\x2dfolders@autostart.service - Pop App Folders...
2024-10-03T15:17:30.146337+00:00 jam systemd[4915]: Starting app-pop\x2dflatpak\x2drepos@autostart.service - Pop Flatpak Repos...
2024-10-03T15:17:30.148117+00:00 jam systemd[4915]: Starting app-print\x2dapplet@autostart.service - Print Queue Applet...
2024-10-03T15:17:30.149663+00:00 jam systemd[4915]: Starting app-user\x2ddirs\x2dupdate\x2dgtk@autostart.service - User folders update...
2024-10-03T15:17:30.151131+00:00 jam systemd[4915]: Starting app-xdg\x2duser\x2ddirs@autostart.service - User folders update...
2024-10-03T15:17:30.152578+00:00 jam systemd[4915]: Starting xdg-document-portal.service - flatpak document portal service...
2024-10-03T15:17:30.160638+00:00 jam systemd[4915]: app-gnome\x2dkeyring\x2dpkcs11@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.161077+00:00 jam systemd[4915]: Condition check resulted in app-gnome\x2dkeyring\x2dpkcs11@autostart.service - Certificate and Key Storage being skipped.
2024-10-03T15:17:30.161910+00:00 jam systemd[4915]: app-gnome\x2dkeyring\x2dsecrets@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.162335+00:00 jam systemd[4915]: Condition check resulted in app-gnome\x2dkeyring\x2dsecrets@autostart.service - Secret Storage Service being skipped.
2024-10-03T15:17:30.163162+00:00 jam systemd[4915]: app-gnome\x2dkeyring\x2dssh@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.163433+00:00 jam systemd[4915]: Condition check resulted in app-gnome\x2dkeyring\x2dssh@autostart.service - SSH Key Agent being skipped.
2024-10-03T15:17:30.164599+00:00 jam systemd[4915]: Started app-im\x2dlaunch@autostart.service - im-launch.
2024-10-03T15:17:30.165235+00:00 jam systemd[4915]: app-nm\x2dapplet@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.165404+00:00 jam systemd[4915]: Condition check resulted in app-nm\x2dapplet@autostart.service - NetworkManager Applet being skipped.
2024-10-03T15:17:30.166079+00:00 jam systemd[4915]: app-orca\x2dautostart@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.166164+00:00 jam systemd[4915]: Condition check resulted in app-orca\x2dautostart@autostart.service - Orca Screen Reader being skipped.
2024-10-03T15:17:30.166433+00:00 jam systemd[4915]: app-org.gnome.SettingsDaemon.DiskUtilityNotify@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.166605+00:00 jam systemd[4915]: Condition check resulted in app-org.gnome.SettingsDaemon.DiskUtilityNotify@autostart.service - gnome-disk-utility notification plugin for GNOME Settings Daemon being skipped.
2024-10-03T15:17:30.167026+00:00 jam systemd[4915]: app-polkit\x2dgnome\x2dauthentication\x2dagent\x2d1@autostart.service: Skipped due to 'exec-condition'.
2024-10-03T15:17:30.167204+00:00 jam systemd[4915]: Condition check resulted in app-polkit\x2dgnome\x2dauthentication\x2dagent\x2d1@autostart.service - PolicyKit Authentication Agent being skipped.
2024-10-03T15:17:30.167796+00:00 jam systemd[4915]: Started app-pop\x2dapp\x2dfolders@autostart.service - Pop App Folders.
2024-10-03T15:17:30.168421+00:00 jam systemd[4915]: Started app-pop\x2dflatpak\x2drepos@autostart.service - Pop Flatpak Repos.
2024-10-03T15:17:30.170311+00:00 jam agent[19513]: Geolocation service in use
2024-10-03T15:17:30.171542+00:00 jam systemd[4915]: Started app-org.pop_os.transition.Notify@autostart.service - Flatpak Transition.
2024-10-03T15:17:30.171924+00:00 jam systemd[4915]: Started app-geoclue\x2ddemo\x2dagent@autostart.service - Geoclue Demo agent.
2024-10-03T15:17:30.172424+00:00 jam systemd[4915]: Started app-at\x2dspi\x2ddbus\x2dbus@autostart.service - AT-SPI D-Bus Bus.
2024-10-03T15:17:30.174192+00:00 jam at-spi-bus-launcher[19538]: Policy to allow eavesdropping in /usr/share/defaults/at-spi2/accessibility.conf +15: Eavesdropping is deprecated and ignored
2024-10-03T15:17:30.174271+00:00 jam at-spi-bus-launcher[19538]: Policy to allow eavesdropping in /usr/share/defaults/at-spi2/accessibility.conf +17: Eavesdropping is deprecated and ignored
2024-10-03T15:17:30.174428+00:00 jam at-spi-bus-launcher[19538]: Kernel is missing AppArmor DBus support.
2024-10-03T15:17:30.175339+00:00 jam systemd[4915]: Started app-print\x2dapplet@autostart.service - Print Queue Applet.
2024-10-03T15:17:30.175508+00:00 jam systemd[4915]: Started app-user\x2ddirs\x2dupdate\x2dgtk@autostart.service - User folders update.
2024-10-03T15:17:30.176092+00:00 jam systemd[4915]: Started app-xdg\x2duser\x2ddirs@autostart.service - User folders update.
2024-10-03T15:17:30.176174+00:00 jam dbus-broker-launch[19538]: Ready
2024-10-03T15:17:30.176276+00:00 jam systemd[4915]: Reached target xdg-desktop-autostart.target - Startup of XDG autostart applications.
2024-10-03T15:17:30.176829+00:00 jam systemd[4915]: Starting xdg-permission-store.service - sandboxed app permission store...
2024-10-03T15:17:30.184508+00:00 jam systemd[4915]: Started xdg-permission-store.service - sandboxed app permission store.
2024-10-03T15:17:30.185938+00:00 jam systemd[4915]: Started xdg-document-portal.service - flatpak document portal service.
2024-10-03T15:17:30.188524+00:00 jam xdg-document-portal[19497]: Ignoring invalid max threads value 4294967295 > max (100000).
2024-10-03T15:17:30.193205+00:00 jam systemd[4915]: Starting xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)...
2024-10-03T15:17:30.289522+00:00 jam systemd[4915]: Created slice app-dbus\x2d:1.314\x2dorg.a11y.atspi.Registry.slice - Slice /app/dbus-:1.314-org.a11y.atspi.Registry.
2024-10-03T15:17:30.307464+00:00 jam systemd[4915]: Started dbus-:1.314-org.a11y.atspi.Registry@0.service.
2024-10-03T15:17:30.312541+00:00 jam at-spi2-registryd[19576]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
2024-10-03T15:17:30.313172+00:00 jam systemd[4915]: Started xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation).
2024-10-03T15:17:30.336829+00:00 jam rtkit-daemon[1585]: Supervising 6 threads of 3 processes of 1 users.
2024-10-03T15:17:30.337296+00:00 jam rtkit-daemon[1585]: message repeated 2 times: [ Supervising 6 threads of 3 processes of 1 users.]
2024-10-03T15:17:30.354113+00:00 jam systemd[4915]: Started xdg-desktop-portal.service - Portal service.
2024-10-03T15:17:30.454675+00:00 jam geoclue[5285]: Failed to query location: Query location SOUP error: Not Found
2024-10-03T15:17:30.478835+00:00 jam cosmic-panel[19305]: com.system76.CosmicAppletStatusArea: Acquired bus name: org.kde.StatusNotifierWatcher
2024-10-03T15:17:30.484205+00:00 jam dbus-broker[910]: A security policy denied :1.358 to send method call /org/freedesktop/NetworkManager/Settings:org.freedesktop.NetworkManager.Settings.LoadConnections to org.freedesktop.NetworkManager.
2024-10-03T15:17:30.485068+00:00 jam systemd[1]: bluetooth.service - Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
2024-10-03T15:17:30.525618+00:00 jam cosmic-panel[19305]: com.system76.CosmicAppletBluetooth: bluetooth subscription finished. exiting...
2024-10-03T15:17:30.530214+00:00 jam cosmic-panel[19305]: Exited with error code 0
2024-10-03T15:17:30.553470+00:00 jam systemd[1]: Starting systemd-timedated.service - Time & Date Service...
2024-10-03T15:17:30.590809+00:00 jam cosmic-panel[19305]: Exited with error code 0
2024-10-03T15:17:30.594256+00:00 jam systemd[1]: Started systemd-timedated.service - Time & Date Service.
2024-10-03T15:17:31.017167+00:00 jam systemd-localed[19300]: The X11 keyboard layout 'gb' is converted to virtual console keymap 'uk'
2024-10-03T15:17:31.023539+00:00 jam systemd-localed[19300]: The X11 keyboard layout 'gb' is converted to virtual console keymap 'uk'
2024-10-03T15:17:31.023993+00:00 jam systemd-localed[19300]: Failed to write X11 keyboard layout, ignoring: Read-only file system
2024-10-03T15:17:31.024183+00:00 jam systemd-localed[19300]: Changed X11 keyboard layout to 'gb' model '' variant 'extd' options ''
2024-10-03T15:17:31.024595+00:00 jam systemd-localed[19300]: Failed to issue method call: Unit systemd-vconsole-setup.service not found.
2024-10-03T15:17:35.722632+00:00 jam systemd[4915]: app-cosmic-com.system76.CosmicAppList-19748.scope: PID 19748 vanished before we could move it to target cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-cosmic-com.system76.CosmicAppList-19748.scope', skipping: No such process
2024-10-03T15:17:35.722882+00:00 jam systemd[4915]: app-cosmic-com.system76.CosmicAppList-19748.scope: No PIDs left to attach to the scope's control group, refusing.
2024-10-03T15:17:35.722952+00:00 jam systemd[4915]: app-cosmic-com.system76.CosmicAppList-19748.scope: Failed with result 'resources'.
2024-10-03T15:17:35.723014+00:00 jam systemd[4915]: Failed to start app-cosmic-com.system76.CosmicAppList-19748.scope - Application launched by COSMIC.
2024-10-03T15:17:38.141367+00:00 jam acpid: client 19289[1000:1000] has disconnected

**Comment by leviport** [comment] 2024-10-14 14:26
Looks like a duplicate of https://github.com/pop-os/cosmic-comp/issues/837

**Closed by leviport** 2024-10-14 14:26 UTC
