### ISSUE TITLE
Apps pinned to the taskbar are too easy to remove.

### ISSUE THREAD

**Issue by LinuxBoy-96** [pop-os/cosmic-epoch#1229] opened 2024-11-08 18:46 UTC
So, everybody (I guess?) knows how to pin a specific app to the taskbar.
Open the app, right-click on the icon, and select "Pin."

The problem is that when clicking on it, we often accidentally drag the icon very slightly, causing it to disappear.
This is also a big problem when we simply want to rearrange the order of these apps. COSMIC is really sensitive in this regard.

I think an app should only be able to be removed in the same way it was pinned in the first place:
Right-click, then "Unpin."

Thanks for considering.

**Comment by leviport** [comment] 2024-11-08 18:47
Duplicate of https://github.com/pop-os/cosmic-panel/issues/247

**Closed by leviport** 2024-11-08 18:47 UTC
