### ISSUE TITLE
Full screen tiling breaks screen

### ISSUE THREAD

**Issue by SAMGARTNER** [pop-os/cosmic-epoch#1253] opened 2024-11-17 17:55 UTC
When you tile a window to the whole screen you get this glitch where a small portion of the bottom screen gets repeated and stacked. 
This happened in the Alpha 3 it doesn't happen every the time, sometimes you have to tile a window multiple times to happen. 
![IMG_0325](https://github.com/user-attachments/assets/0e8582b4-c3d7-4931-93a7-056c4e91f59b)

**Comment by leviport** [comment] 2024-11-18 15:49
I believe this is a duplicate of https://github.com/pop-os/cosmic-comp/issues/499

**Closed by leviport** 2024-11-18 15:49 UTC
