### ISSUE TITLE
Desktop locks up with HDD when changing a setting rapidly

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-epoch#608] opened 2024-08-11 10:52 UTC
Reproduce:
1. Choose a setting that can rapidly be changed (active window hint, colour, etc)
2. Rapidly change the value
3. Watch drive usage skyrocket

Whilst this bug hasn't been presenting itself with lockups on SSDs, as it currently stands this seems to be causing excessive writes to drives, so I am concerned about potential damage if this issue is left unresolved.

Video Demonstration:
https://youtu.be/WoyzaLW52No

**Comment by git-f0x** [comment] 2024-08-11 11:03
Related issue: pop-os/cosmic-settings#474.

**Comment by mmstick** [comment] 2024-08-11 18:35
Duplicate of above. Subscribe to the cosmic-settings issue above.

**Closed by mmstick** 2024-08-11 18:34 UTC
