### ISSUE TITLE
[Feature Request] Add battery percentage to Power&Battery applet or add battery-percentage applet

### ISSUE THREAD

**Issue by TundraFox907** [pop-os/cosmic-epoch#1148] opened 2024-10-17 21:15 UTC
Maybe this is just a personal preference, but I really like being able to see the battery percentage as a number next to the slowly draining battery icon on a laptop. It's a feature on the old GNOME-based Cosmic (picture below) and I'm not keen on losing it come the new release of COSMIC. I find it far more helpful to be able to see battery percentage at a glance rather than having to guess from the icon or click on / mouse over the applet. 

![image](https://github.com/user-attachments/assets/3e7238a6-29cc-40a6-bf44-1dd77419ef39)

I know next to nothing about the nuts and bolts of coding this sort of thing so I'm unsure if it would be easier to make that part of the P&B applet or making it a separate applet. 

Experientially, I don't think it makes a difference if the feature is a separate applet or part of the P&B applet, but I can see an argument being made that a random floating number should stay next to the thing it refers to if the user reorders their applets, and I can also see an argument for keeping it separate to make a more modular interface and allow a user to put the percentage wherever they please regardless of where the P&B applet is.

**Comment by leviport** [comment] 2024-10-17 21:23
Duplicate of https://github.com/pop-os/cosmic-applets/issues/617

**Closed by leviport** 2024-10-17 21:23 UTC
