### ISSUE TITLE
[Feature Request] Support for fcitx5 or ibus ime

### ISSUE THREAD

**Issue by engineerNg** [pop-os/cosmic-epoch#305] opened 2024-05-07 22:01 UTC
fcitx5 and ibus work fine under pop wayland session, and should be fine to be implemented under COSMIC.

**Comment by jacobgkau** [comment] 2024-05-08 03:07
I'm closing this as a duplicate of https://github.com/pop-os/cosmic-epoch/issues/104.

Please let me know if you think that issue doesn't cover what you're asking for. (As mentioned in the issue, IBus is very GNOME-centric, so Fcitx is what would be primarily supported.)

**Closed by jacobgkau** 2024-05-08 03:07 UTC
